name: Container images generator

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  container-images:
    if: ${{ github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 12.x
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: project-openubl/ublhub-ui/ublhub-ui
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: projectopenubl/ublhub-ui
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: quay.io
          name: projectopenubl/ublhub-ui
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
